import = ["/home/mike/.cache/colorschemes/alacritty.toml"]

[font]
size = 9.0

[font.bold]
family = "Hurmit Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hurmit Nerd Font Mono"
style = "Regular Italic"

[font.normal]
family = "Hurmit Nerd Font Mono"
style = "Regular"

[window]
dynamic_padding = true

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
