import:
  - ~/.cache/colorschemes/alacritty.yml

window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 0
    y: 0
  dynamic_padding: true

font:
  normal:
    family: Hurmit Nerd Font Mono
    style: "Regular"
  bold:
    family: Hurmit Nerd Font Mono
    style: "Bold"
  italic:
    family: Hurmit Nerd Font Mono
    style: "Regular Italic"
  size: 11.0
