colors:
  primary:
    background:        '{colorbg}'
    foreground:        '{colorfg}'
  cursor:
    text:   '{colorbg}'
    cursor: '{colorfg}'
  bright:
    # use light gray (for zsh-autocomplete text)
    black:   '{color8}'
    red:     '{color1}'
    green:   '{color2}'
    yellow:  '{color3}'
    blue:    '{color4}'
    magenta: '{color5}'
    cyan:    '{color6}'
    white:   '{color7}'
  normal:
    # use black rather than default light gray (color8) (for black colors in eg vim airline)
    black:   '{color0}'
    red:     '{color9}'
    green:   '{color10}'
    yellow:  '{color11}'
    blue:    '{color12}'
    magenta: '{color13}'
    cyan:    '{color14}'
    white:   '{color15}'
